name: ci workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: Test
          verbosity: Verbose
          arguments: |
            configuration: Release
            nuget_useinprocessclient: true
            settings_skipverification: true
            settings_skippackageversioncheck: true

  coverage:
    name: coverage
    needs: test
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: CalculateCoverage
          verbosity: Verbose
          arguments: |
            configuration: Debug
            nuget_useinprocessclient: true
            settings_skipverification: true
            settings_skippackageversioncheck: true
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/artifacts/coverage.opencover.xml
          fail_ci_if_error: true
            